drop table Kind if exists;
drop table BenutzerKitaRecht if exists;
drop table Kita if exists;
drop table Benutzer if exists;


create table Benutzer (
	id bigint generated by default as identity (start with 1), 
	alias varchar(255), 
	firstName varchar(255), 
	lastName varchar(255), 
	password varchar(255), 
	role varchar(255), 
	traeger varchar(255), 
	primary key (id)
);

create table Kita (
	id bigint generated by default as identity (start with 1), 
	name varchar(255), primary key (id)
);


create table BenutzerKitaRecht (
	id bigint generated by default as identity (start with 1), 
	recht varchar(255), 
	benutzer_id bigint, 
	kita_id bigint, 
	primary key (id)
);


create table Kind (
	id bigint generated by default as identity (start with 1), 
	firstName varchar(255), 
	lastName varchar(255), 
	kita_id bigint,
	primary key (id)
);

alter table BenutzerKitaRecht add constraint rechte_benutzer_fk foreign key (benutzer_id) references Benutzer;
alter table BenutzerKitaRecht add constraint rechte_kita_fk foreign key (kita_id) references Kita;
alter table Kind add constraint kind_kita_fk foreign key (kita_id) references Kita;


